#
# Deployment Test Script
#

# Enable ADCS components
cmd("GENERIC_CSS_DEBUG GENERIC_CSS_ENABLE_CC")
cmd("GENERIC_FSS_DEBUG GENERIC_FSS_ENABLE_CC")
cmd("GENERIC_IMU_DEBUG GENERIC_IMU_ENABLE_CC")
cmd("GENERIC_MAG_DEBUG GENERIC_MAG_ENABLE_CC")
cmd("GENERIC_TORQUER_DEBUG GENERIC_TORQUER_ENABLE_CC")
cmd("NOVATEL_OEM615_DEBUG NOVATEL_OEM615_ENABLE_CC")
wait(3)

# Prepare scenario, i.e. spin up spacecraft
cmd("GENERIC_REACTION_WHEEL_DEBUG GENERIC_RW_SET_TORQUE_CC with WHEEL_NUMBER 0, TORQUE 2")
wait_check_tolerance("GENERIC_ADCS_DEBUG GENERIC_ADCS_AD WBN_X", -0.10, 0.01, 120)
cmd("GENERIC_REACTION_WHEEL_DEBUG GENERIC_RW_SET_TORQUE_CC with WHEEL_NUMBER 0, TORQUE 0")

cmd("GENERIC_REACTION_WHEEL_DEBUG GENERIC_RW_SET_TORQUE_CC with WHEEL_NUMBER 1, TORQUE 4")
wait_check_tolerance("GENERIC_ADCS_DEBUG GENERIC_ADCS_AD WBN_Y", -0.10, 0.01, 120)
cmd("GENERIC_REACTION_WHEEL_DEBUG GENERIC_RW_SET_TORQUE_CC with WHEEL_NUMBER 1, TORQUE 0")

cmd("GENERIC_REACTION_WHEEL_DEBUG GENERIC_RW_SET_TORQUE_CC with WHEEL_NUMBER 2, TORQUE -6")
wait_check_tolerance("GENERIC_ADCS_DEBUG GENERIC_ADCS_AD WBN_Z", 0.10, 0.01, 120)
cmd("GENERIC_REACTION_WHEEL_DEBUG GENERIC_RW_SET_TORQUE_CC with WHEEL_NUMBER 2, TORQUE 0")
wait(30)

## Enable BDOT mode to detumble
#cmd("GENERIC_ADCS_DEBUG GENERIC_ADCS_SET_MODE_CC with GNC_MODE 'BDOT_MODE'")
#wait(3)
#
## Wait on transition until all axis reported under 3 degrees angular rate
#wait_check_tolerance("GENERIC_ADCS_DEBUG GENERIC_ADCS_AD WBN_X", 0.0, 0.015, 120)
#wait_check_tolerance("GENERIC_ADCS_DEBUG GENERIC_ADCS_AD WBN_Y", 0.0, 0.015, 120)
#wait_check_tolerance("GENERIC_ADCS_DEBUG GENERIC_ADCS_AD WBN_Z", 0.0, 0.015, 120)
#
## Check again to be sure
#wait_check_tolerance("GENERIC_ADCS_DEBUG GENERIC_ADCS_AD WBN_X", 0.0, 0.015, 10)
#wait_check_tolerance("GENERIC_ADCS_DEBUG GENERIC_ADCS_AD WBN_Y", 0.0, 0.015, 10)
#wait_check_tolerance("GENERIC_ADCS_DEBUG GENERIC_ADCS_AD WBN_Z", 0.0, 0.015, 10)

# Set sun safe mode
cmd("GENERIC_ADCS_DEBUG GENERIC_ADCS_SET_MODE_CC with GNC_MODE 'SUNSAFE_MODE'")
